export const TOOLTIP_NAVBAR = [
  { Name: "notification-icon", isCount: true, tooltipText: "Thông báo" },
  { Name: "helper-icon", isCount: true, tooltipText: "Trợ giúp" },
  { Name: "sevice-icon", isCount: true, tooltipText: "Tính năng khác" }
];
export const PAGING_OPTION = {
  pageSize: 15,
  pageNumber: 1,
  workingShiftFilter: null,
  customParams: []
};
export const DATATYPENAME_TIME = [
  { Name: "ShiftStartTime" },
  { Name: "TimekeepingShiftStart" },
  { Name: "TimekeepingShiftEnd" },
  { Name: "ShiftEndTime" },
  { Name: "TimekeepingOutShiftStart" },
  { Name: "TimekeepingOutShiftEnd" },
  { Name: "BreakTimeBetweenShiftStart" },
  { Name: "TimekeepingBreakTimeBetweenShifts" },
  { Name: "BreakTimeBetweenShiftEnd" },
  { Name: "BreakTimeBetweenShift" }
];
export const OPTION_TOAST_MESS = {
  toastClassName: "custom-toast-class",
  position: "bottom-right",
  timeout: 2000,
  closeOnClick: false,
  pauseOnFocusLoss: false,
  pauseOnHover: false,
  draggable: true,
  draggablePercent: 0.6,
  showCloseButtonOnHover: true,
  hideProgressBar: true,
  closeButton: false,
  icon: true,
  rtl: false,
};

export const OPTION_TOAST_MESS_SUCCESS = {
  ...OPTION_TOAST_MESS,
  toastClassName: "custom-success-toast-class",
  bodyClassName: "custom-body",
  iconClass: 'success-icons',
};

export const OPTION_TOAST_MESS_ERROR = {
  ...OPTION_TOAST_MESS,
  toastClassName: "custom-error-toast-class",
  bodyClassName: "custom-error-body",
  iconClass: 'success-error-icons',
};

export const PROPETY_TABLE = [
  // Mã ca
  {
    Field: "WorkingShiftCode",
    Caption: "Mã ca",
    Width: 220,
    Fixed: true,
    AllowFixing: false,
    FixPosition: "",
    Alignemnt: "left",
    Format: "",
    DataType: "",
    IsCheck: true,
    OrderColumn: 1,
  },
  // Tên ca
  {
    Field: "WorkingShiftName",
    Caption: "Tên ca",
    Width: 220,
    Fixed: false,
    FixPosition: "",
    Alignemnt: "left",
    Format: "",
    DataType: "",
    IsCheck: true,
    OrderColumn: 2,
  },
  // Giờ bắt đầu ca 
  {
    Field: "ShiftStartTime",
    Caption: "Giờ bắt đầu ca ",
    Width: 220,
    Fixed: false,
    FixPosition: "",
    Alignemnt: "center",
    Format: "HH:mm",
    DataType: "date",
    IsCheck: true,
    OrderColumn: 3,
  },
  // Chấm vào đầu ca từ
  {
    Field: "TimekeepingShiftStart",
    Caption: "Chấm vào đầu ca từ",
    Width: 220,
    Fixed: false,
    FixPosition: "",
    Alignemnt: "center",
    Format: "HH:mm",
    DataType: "date",
    IsCheck: true,
    OrderColumn: 4,
  },

  // Chấm vào đầu ca đến
  {
    Field: "TimekeepingShiftEnd",
    Caption: "Chấm vào đầu ca đến",
    Width: 220,
    Fixed: false,
    FixPosition: "",
    Alignemnt: "center",
    Format: "HH:mm",
    DataType: "date",
    IsCheck: true,
    OrderColumn: 5,
  },
  // Giờ kết thúc ca
  {
    Field: "ShiftEndTime",
    Caption: "Giờ kết thúc ca",
    Width: 220,
    Fixed: false,
    FixPosition: "",
    Alignemnt: "center",
    Format: "HH:mm",
    DataType: "date",
    IsCheck: true,
    OrderColumn: 6,
  },

  // Chấm ra cuối ca từ
  {
    Field: "TimekeepingOutShiftStart",
    Caption: "Chấm ra cuối ca từ",
    Width: 220,
    Fixed: false,
    FixPosition: "",
    Alignemnt: "center",
    Format: "HH:mm",
    DataType: "date",
    IsCheck: true,
    OrderColumn: 7,
  },
  // Chấm ra cuối ca đến
  {
    Field: "TimekeepingOutShiftEnd",
    Caption: "Chấm ra cuối ca đến",
    Width: 220,
    Fixed: false,
    FixPosition: "",
    Alignemnt: "center",
    Format: "HH:mm",
    DataType: "date",
    IsCheck: true,
    OrderColumn: 8,
  },
  // Giờ bắt đầu nghỉ giữa ca
  {
    Field: "BreakTimeBetweenShiftStart",
    Caption: "Giờ bắt đầu nghỉ giữa ca",
    Width: 220,
    Fixed: false,
    FixPosition: "",
    Alignemnt: "center",
    Format: "HH:mm",
    DataType: "date",
    IsCheck: true,
    OrderColumn: 9,
  },
  // Chấm ra nghỉ giữa ca từ
  {
    Field: "TimekeepingBreakTimeBetweenShifts",
    Caption: "Chấm ra nghỉ giữa ca từ",
    Width: 220,
    Fixed: false,
    FixPosition: "",
    Alignemnt: "center",
    Format: "HH:mm",
    DataType: "date",
    IsCheck: true,
    OrderColumn: 10,
  },
  // Giờ kết thúc nghỉ giữa ca
  {
    Field: "BreakTimeBetweenShiftEnd",
    Caption: "Giờ kết thúc nghỉ giữa ca",
    Width: 220,
    Fixed: false,
    FixPosition: "",
    Alignemnt: "center",
    Format: "HH:mm",
    DataType: "date",
    IsCheck: true,
    OrderColumn: 11,
  },
  // Chấm vào nghỉ giữa ca đến
  {
    Field: "BreakTimeBetweenShift",
    Caption: "Chấm vào nghỉ giữa ca đến",
    Width: 220,
    Fixed: false,
    FixPosition: "",
    Alignemnt: "center",
    Format: "HH:mm",
    DataType: "date",
    IsCheck: true,
    OrderColumn: 12,
  },
  // Ngày công
  {
    Field: "WorkingDay",
    Caption: "Ngày công",
    Width: 220,
    Fixed: false,
    FixPosition: "",
    Alignemnt: "right",
    Format: "#0.0",
    DataType: "number",
    IsCheck: true,
    OrderColumn: 13,
  },
  // Giờ công
  {
    Field: "WorkingHour",
    Caption: "Giờ công",
    Width: 220,
    Fixed: false,
    FixPosition: "",
    Alignemnt: "right",
    Format: "#0.0",
    DataType: "number",
    IsCheck: true,
    OrderColumn: 14,
  },
  {
    Field: "WeekendSalaryCoefficient",
    Caption: "Hệ số ngày nghỉ",
    Width: 220,
    Fixed: false,
    FixPosition: "",
    Alignemnt: "right",
    Format: "#0.0",
    DataType: "number",
    IsCheck: true,
    OrderColumn: 15,
  },
  {
    Field: "HolidayPayCoefficient",
    Caption: "Hệ số ngày lễ",
    Width: 220,
    Fixed: false,
    FixPosition: "",
    Alignemnt: "right",
    Format: "#0.0",
    DataType: "number",
    IsCheck: true,
    OrderColumn: 16,
  },
];
export const PROPETY_OPERATOR = [
  {Name: 'Chứa' , operation : 'contains'},
  {Name: 'Không Chứa',operation: 'notcontains'},
  {Name: 'Bằng', operation: 'equals'}
];
export const PROPETY_OPERATORNUMBER = [
  {Name: 'Khác',operation: 'other'},
  {Name: 'Bằng', operation: 'equals'},
  {Name: 'Lớn hơn', operation: 'greater'},
  {Name: 'Nhỏ hơn', operation: 'smaller'}
];
export const PROPETY_FILTER = [
  {
    Caption: "Mã ca",
    ValueField: "WorkingShiftCode",
    isCheck: false,
    operation: "contains",
    type: "",
    value: null,
  },
  {
    Caption: "Tên ca làm",
    ValueField: "WorkingShiftName",
    isCheck: false,
    operation: "contains",
    type: "",
    value: null,
  },
  {
    Caption: "Giờ bắt đầu ca ",
    ValueField: "ShiftStartTime",
    isCheck: false,
    operation: "other",
    type: "date",
    value: null,
  },
  {
    Caption: "Chấm vào đầu ca từ",
    ValueField: "TimekeepingShiftStart",
    isCheck: false,
    operation: "other",
    type: "date",
    value: null,
  },
  {
    Caption: "Chấm vào đầu ca đến",
    ValueField: "TimekeepingShiftEnd",
    isCheck: false,
    operation: "other",
    type: "date",
    value: null,
  },
  {
    Caption: "Giờ kết thúc ca",
    ValueField: "ShiftEndTime",
    isCheck: false,
    operation: "other",
    type: "date",
    value: null,
  },
  {
    Caption: "Chấm ra cuối ca từ",
    ValueField: "TimekeepingOutShiftStart",
    isCheck: false,
    operation: "other",
    type: "date",
    value: null,
  },
  {
    Caption: "Chấm ra cuối ca đến",
    ValueField: "TimekeepingOutShiftEnd",
    isCheck: false,
    operation: "other",
    type: "date",
    value: null,
  },
  {
    Caption: "Giờ bắt đầu nghỉ giữa ca",
    ValueField: "BreakTimeBetweenShiftStart",
    isCheck: false,
    operation: "other",
    type: "date",
    value: null,
  },
  {
    Caption: "Chấm ra nghỉ giữa ca từ",
    ValueField: "TimekeepingBreakTimeBetweenShifts",
    isCheck: false,
    operation: "other",
    type: "date",
    value: null,
  },
  {
    Caption: "Giờ kết thúc nghỉ giữa ca",
    ValueField: "BreakTimeBetweenShiftEnd",
    isCheck: false,
    operation: "other",
    type: "date",
    value: null,
  },
  {
    Caption: "Chấm vào nghỉ giữa ca đến",
    ValueField: "BreakTimeBetweenShift",
    isCheck: false,
    operation: "other",
    type: "date",
    value: null,
  },
  {
    Caption: "Ngày công",
    ValueField: "WorkingDay",
    isCheck: false,
    operation: "equals",
    type: "number",
    value: "",
  },
  {
    Caption: "Giờ công",
    ValueField: "WorkingHour",
    isCheck: false,
    operation: "equals",
    type: "number",
    value: "",
  },
  {
    Caption: "Hệ số ngày nghỉ",
    ValueField: "WeekendSalaryCoefficient",
    isCheck: false,
    operation: "equals",
    type: "number",
    value: "",
  },
  {
    Caption: "Hệ số ngày lễ",
    ValueField: "HolidayPayCoefficient",
    isCheck: false,
    operation: "equals",
    type: "number",
    value: "",
  },
];
export const DEFAULT_VALUE = {
  WorkingShiftName: "",
  WorkingShiftCode: "",
  ShiftStartTime: "08:30:00",
  TimekeepingShiftStart: "07:00:00",
  TimekeepingShiftEnd: "09:00:00",
  ShiftEndTime: "17:30:00",
  TimekeepingOutShiftStart: "16:30:00",
  TimekeepingOutShiftEnd: "18:30:00",
  WorkingHour: 9,
  WorkingDay: 1,
  WeekdaySalaryCoefficients: 1,
  WeekendSalaryCoefficient: 1,
  HolidayPayCoefficient: 2,
}
